### ISSUE TITLE
Show job chain on Dashboard

### ISSUE THREAD

**Issue by lamira-stack** [OT-Hub/OTHub#121]
I think it would be great if we could be able to see the chain ot the jobs we win on the My Nodes Dashboard

Something like this:

![mockup](https://user-images.githubusercontent.com/71933691/132053527-f591ed13-a786-4acb-ae1d-13f418b58ef9.PNG)

**Comment by lukeskinner** [comment]
Great idea! Thank you :)

I'm gonna see if I can plan out my next update for othub and will try get this in with it
