### ISSUE TITLE
New RPC for gnosis Chain

### ISSUE THREAD

**Issue by mucke12** [OT-Hub/OTHub#147]
Hi Luke,

hope you are fine!
Would it be possible to update the gnosis RPC to https://rpc.ankr.com/gnosis so Noderunner can payout their rewards. That would be really kind of you.

Greetings

OT-Community

**Comment by lukeskinner** [comment]
let me see what I can do

**Comment by lukeskinner** [comment]
thanks for reaching out

**Comment by lukeskinner** [comment]
I've cleaned up the RPCs as we had a lot of old dead ones on https://othub.origin-trail.network/system/rpc

I have put that ankr link in to othub - that rpc endpoint works perfectly at first impressions.

I have put the syncing of data back to November 2022 for xdai as I heard that's when it may have gone. Check back on it in 24 hours and we will see how the sync has gone - probably not worth retrying your payouts until it's synced again.

**Comment by mucke12** [comment]
Hey Luke, thank you very much. The whole community appreciate this 💪

**Comment by mucke12** [comment]
Hey Luke, thanks again. its seem it has synced till 13/01/2023 22:59 but stopt after that. I think that was also the time when you started the resync?

Greetings

LuKu

**Comment by lukeskinner** [comment]
I'm giving it another kick/reboot for good measure. Sorry I haven't had a chance to check on it this weekend until now.

It has to sync data in a few parts, part 1 of this sync is at block number 25967283 Jan-14-2023 10:40:20 PM +UTC). It did seem to be paused around the date you provided but unsure why as no errors in the logs - it's moving again now.

**Comment by lukeskinner** [comment]
Gnosis sync is up-to-date.
87 jobs were picked up since I rebooted it. 

I can also see some jobs for today coming through

**Comment by mucke12** [comment]
Thanks again Luke. Seems to work and synced now =)
