### ISSUE TITLE
v5api.othub.info down

### ISSUE THREAD

**Issue by mucke12** [OT-Hub/OTHub#149]
Hi Luke, its me again =)

it seems like that there is a problem with v5api.othub.info

If you find some time, could you have a look at it? Thanks again

Greetings

LuKu

**Comment by lukeskinner** [comment]
hello! 

Thanks again for the report, I'm a bit slow as I've ended up with thousands of notifications on github even though I barely use this website currently! 

Give it up to 24 hours and it'll come back - it's a DNS change which is a bit variable for people
